Repository ant-design/ant-design-pro, pull requests merged in 2019-10, with the labels that each got.

#5377 fix: right-align the right content of topmenu
  src/components/GlobalHeader/index.less
Labels: bug

#5386 fix(package.json): npm run format-imports adapt windows
  package.json
Labels: bug

#5384 feat: ignore .history folder
  .eslintignore
  .prettierignore
Labels: enhancement

#5448 bugfix: auto reload Authorized
  src/utils/authority.ts
Labels: bugfix

#5455 chore: github action for comment rebase
  .github/workflows/rebase.yml
Labels: chore

#5461 Fix: Reflected XSS Vulnerability in login after-action script
  src/models/login.ts
Labels: FIX

#5452 Feat: Add authorized router demo
  config/config.ts
  src/components/Authorized/Authorized.tsx
  src/layouts/BasicLayout.tsx
  src/locales/en-US/menu.ts
  src/locales/pt-BR/menu.ts
  src/locales/zh-CN/menu.ts
  src/locales/zh-TW/menu.ts
  src/pages/Admin.tsx
  src/utils/utils.ts
Labels: Feat

#5484 chrome: remove serve env
  config/config.ts
  package.json
Labels: chrome
