Repository ant-design/ant-design-pro, pull requests merged in 2019-12, with the labels that each got.

#5694 fix: webpackChain config type fix
  config/plugin.config.ts
Labels: bug

#5690 doc: fix Use bash error.
  README.fr-FR.md
  README.ja-JP.md
  README.md
  README.pt-BR.md
  README.ru-RU.md
  README.tr-TR.md
  README.zh-CN.md
Labels: doc

#5679 doc: update navigation
  README.fr-FR.md
  README.ja-JP.md
  README.pt-BR.md
  README.ru-RU.md
  README.zh-CN.md
Labels: doc

#5534 dep: upgrade dva to 2.6.0-beta.16, fix warning
  package.json
  src/models/login.ts
Labels: Inactive, dep

#5723 fix: authority covered by routes behind
  src/pages/Authorized.tsx
  src/utils/utils.test.ts
  src/utils/utils.ts
Labels: bug

#5746 bugfix: NoticeIcon Tabs activeKey error
  src/components/NoticeIcon/index.tsx
Labels: bugfix
