Repository ant-design/ant-design-pro, pull requests merged in 2025-07, with the labels that each got.

#11528 fix: 404 path in routes.ts
  config/routes.ts
Labels: 🛑 bug, size:XS

#11531 chore(deps): update and remove unused deps
  package.json
Labels: dependencies, size:S, lgtm

#11534 docs: fix readme umi version
  README.md
  README.zh-CN.md
Labels: 😸Documentation, size:S, lgtm
